lib/rspec/parameterized/table_syntax.rb
spec/parametarized_spec.rb

In case of using RSpec::Parameterized::TableSyntax, I can't use nil / true / false for 1st column.
It occurs syntax error.
```
/Users/ryonext/dev/rspec-parameterized/lib/rspec/parameterized.rb:139:in `define_cases': undefined method `to_params' for true:TrueClass (NoMethodError)
from /Users/ryonext/dev/rspec-parameterized/lib/rspec/parameterized.rb:74:in `with_them'
```

Accept nil/boolean for 1st column

---

lib/rspec/parameterized.rb
spec/parametarized_spec.rb

test all combinations of values.
You can be described as follows.
```
where(:a, :b, :c) do
[[1, 5, 2], [1, 5, 4], [1, 7, 2], [1, 7, 4], [1, 9, 2], [1, 9, 4], [3, 5, 2], [3, 5, 4], [3, 7, 2], [3, 7, 4], [3, 9, 2], [3, 9, 4]]
end
where(a: [1, 3], b: [5, 7, 9], c: [2, 4])
```

allow hash arguments

---

lib/rspec/parameterized.rb

Remove methods used by only `where_table` feature.

Remove unnecessary methods

---

README.md
lib/rspec/parameterized.rb
spec/parametarized_spec.rb

Add `params` and `all_params` methods in order to browse parameter values in with_them block.
refs #27

Enable to browse parameter values in with_them block

---

rspec-parameterized.gemspec

In order to display a link in rubygems.org
homepage is empty :crying_cat_face: 
homepage url is filled
This change will be reflected in the next release

Add homepage url in gemspec

---

lib/rspec/parameterized.rb

`RSpec::Parameterized::ExampleGroupMethods` calls `RSpec::Core::ExampleGroup.describe` via `.with_them`.
At that time, the metadata of ExapmleGroup is used `Proc#sorce_location` of block that have been passed to `RSpec::Core::ExampleGroup.describe`.
https://github.com/rspec/rspec-core/blob/v3.5.2/lib/rspec/core/metadata.rb#L150
This is the line that `RSpec::Parameterized::ExampleGroupMethods` was calling `RSpec::Core::ExampleGroup.describe`, not the line where you have to call `RSpec::Parameterized::ExampleGroupMethods.with_them`.
For example, if I use `RspecJUnitFormatter`, the difference of the output is 'classname' and 'file' in each testcase.
before:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="rspec" tests="55" failures="0" errors="0" time="0.020887" …
```

Set the caller of `.with_them` to metadata of ExampleGroup

---

.travis.yml
lib/rspec/parameterized/table_syntax.rb
rspec-parameterized.gemspec
spec/parametarized_spec.rb

`Fixnum` and `Bignum` are deprecated since ruby 2.4
```sh
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin13]
$ bundle exec rspec
(snip)
/Users/sue445/dev/workspace/github.com/tomykaira/rspec-parameterized/lib/rspec/parameterized/table_syntax.rb:30: warning: constant ::Fixnum is deprecated
/Users/sue445/dev/workspace/github.com/tomykaira/rspec-parameterized/lib/rspec/parameterized/table_syntax.rb:34: warning: constant ::Bignum is deprecated
```

Fix deprecation warning on ruby 2.4.0

---

README.md
lib/rspec/parameterized.rb
spec/parametarized_spec.rb

This PR allows users to specify custom descriptions using magic argument :case_name
```
describe "Custom names for regular syntax" do
where(:case_name, :a, :b, :answer) do
[
["positive integers",  6,  2,  8],
["negative integers", -1, -2, -3],
[   "mixed integers", -5,  3, -2],
]
end
with_them do
it "should do additions" do
expect(a + b).to eq answer
end
end
```
For hash syntax you can specify a lambda that would be fed with other arguments:
```
describe "Custom naming for hash syntax" do
where(case_names: ->(a, b, c){"#{a} + #{b} + #{c}"}, a: [1, 3], b: [5, 7, 9], c: [2, 4])
with_them do
it "sum is even" do
expect(a + b + c).to be_even
end
end
end
```
Maybe not the most elegant solution, but I've been using it for a while and it's better then nothing.

Customizable description

---

README.md
lib/rspec/parameterized.rb
spec/parametarized_spec.rb

Context: I'm using rspec for high-level integration tests and they very often carry a lot of verbose input arguments (such as hashes or arrays). For those cases I found it very convenient to represent tests as a hash of hashes:
```
describe "Verbose syntax" do
where do
{
"positive integers" => {
a: 1,
b: 2,
answer: 3,
},
"negative_integers" => {
a: -1,
b: -2,
answer: -3,
},
"mixed_integers" => {
a: 3,
b: -3,
answer: 0,
},
}
end
with_them do
it "should do additions" do
expect(a + b).to eq answer
end
end
end
```
or if you want some (almost) actual usage example:
```
where do
{
'the mots simple combinations of settings' => {
settings: {
'my_user_1' => 'none',
'my_user_2' => 'none'
},
outcome: %w(my_user_1 my_user_2)
},
'a little bit more interesting case' => {
settings: {
'my_user_1' => …
```

Verbose test syntax

---

lib/rspec/parameterized/table_syntax.rb
rspec-parameterized.gemspec

I developed `binding_ninja` simple and lightweight alternative of `binding_of_caller`.
https://github.com/joker1007/binding_ninja
I replaced table_syntax implementation with `binding_ninja`

Replace binding_of_caller with binding_ninja

---

rspec-parameterized.gemspec

details #45 
When using `binding_ninja` v0.2.0, rspec is failed. 
This problem is fixed at v0.2.1. So I think that it would be better to avoid v0.2.0
Close #45

Use binding_ninja v0.2.1+

---

.travis.yml
gemfiles/rspec-head.gemfile
gemfiles/rspec3.3.gemfile
rspec-parameterized.gemspec

Support jruby

---

.travis.yml

- See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration for more details

Travis: Remove unused sudo: false directive

---

.travis.yml

This PR updates the CI matrix to use latest JRuby, **9.2.8.0**.
[JRuby 9.2.8.0 release blog post](https://www.jruby.org/2019/08/12/jruby-9-2-8-0.html)

CI: Use latest jruby

---

lib/rspec/parameterized.rb
lib/rspec/parameterized/arg.rb
lib/rspec/parameterized/helper_methods.rb
lib/rspec/parameterized/lazy_arg.rb
lib/rspec/parameterized/ref_arg.rb
spec/parametarized_spec.rb

usage:
``` ruby
describe "ref and lazy" do
let(:one) { 1 }
let(:four) { 4 }
where(:a, :b, :answer) do
[
[ref(:one), ref(:four), lazy { two + three }],
]
end
with_them do
context "define two and three after where block" do
let(:two) { 2 }
let(:three) { 3 }
it "should do additions" do
expect(a + b).to eq answer
end
end
end
end
```
This change should be a workaround for issue #8.

Add new parameter type: ref and lazy.

---

lib/rspec/parameterized/lazy_arg.rb
lib/rspec/parameterized/ref_arg.rb

This PR makes description  readable.
Currently, failed spec looks like:
```
Failures:
1) RSpec::Parameterized lazy a: #<RSpec::Parameterized::RefArg:0x00007fd356a1ff50 @symbol=:one>, b: #<RSpec::Parameterized::RefArg:0x00007fd356a1ff28 @symbol=:four>, answer: #<RSpec::Parameterized::LazyArg:0x00007fd356a1fed8 @block=#<Proc:0x00007fd356a1fe88@/Users/shinji_yoshida/workspace/rspec-parameterized/spec/parametarized_spec.rb:224>> define two and three after where block fail
Failure/Error: expect(a + b + 1).to eq answer
expected: 5
got: 6
(compared using ==)
```
After This PR applied, failed spec will look like:
```
Failures:
1) RSpec::Parameterized lazy a: one, b: four, answer: lazy { two + three } define two and three after where block fail
Failure/Error: expect(a + b + 1).to eq answer …
```

override inspect() of ref and lazy to make description readable

---

lib/rspec/parameterized.rb
lib/rspec/parameterized/example_helper_methods.rb
spec/parametarized_spec.rb

Implements `recursive_apply` method that is calls apply method of Arg class to children of Array or Hash parameters. 
When I want to use array or hash parameters with ref or lazy, it didn't  applies properly.
```ruby
let(:foo) { 1 }
where(:values, :answer) do
[
[[ref(:foo), 2], 2],
]
end
with_them do
it { expect(values.sum).to eq(answer) } # values => [:foo, 2] 
end
```

Changes to apply method calls recursively when parameter is Array or Hash.

---

rspec-parameterized.gemspec

I want to make MFA mandatory for gem security (supply chain attack)
https://blog.rubygems.org/2022/06/13/making-packages-more-secure.html
MFA is requested when `rake release` is running
```
$ bundle exec rake release
(snip)
You have enabled multi-factor authentication. Please enter OTP code.
Code:
```
Please enable MFA on own account 🙏 
https://rubygems.org/settings/edit

Made MFA mandatory for gem releases

---

.github/workflows/rspec.yml
lib/rspec/parameterized/table_syntax.rb
rspec-parameterized.gemspec

ref #80
`Refinement#include` is removed since ruby 3.2
https://bugs.ruby-lang.org/issues/17429
So I use `Refinement#import_methods` on ruby 3.2+
@joker1007 This patch actually works, but it's a little dirty...
What do you think?
Close #80

Support Ruby 3.2

---

rspec-parameterized.gemspec

The rubygems.org page shows that the license is unknown because it references the .gemspec file which omits the license metadata. When reviewing the licenses for a project, I noticed that the gem wasn't showing a license, even though the repo mentions it's MIT licensed. It's possible others are also running into this, so I've added the license-ref in the .gemspec file.

Reference LICENSE file in .gemspec

---

lib/rspec/parameterized/version.rb
rspec-parameterized.gemspec

I merged #87 and published as v1.0.1. 
But, the licensing statement in the https://rubygems.org/gems/rspec-parameterized/versions/1.0.1 is odd. (maybe https://rubygems.org/ doesn't support LicenseRef...?)
So I decided to specify the license directly

Hard-code the license name
